title: 這裡有重點
author: meyu
email: yrrvknone@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Let's change the _config.yml so it's a perfect fit for your new blog. 
  First, we need to use a blog-ready theme. 
  For this activity, we will use a theme named minima.
theme: minima

# social links
twitter_username: meyu_lee
github_username:  meyu

show_excerpts: true # set to false to remove excerpts on the homepage
